"""M1 synthetic transaction reference, NOT a Hybrid market runtime.

Only callers supplying their own isolated SQLite connection can use this module.
Amounts and fills are synthetic fixtures, not prices generated by this module.
Real protection/entry integration, sizing and evidence admission belong to M5.
"""

from contextlib import contextmanager
import hashlib
import heapq
import json
import math
import sqlite3

from .hybrid_contracts import DecisionTimeline
from .hybrid_identity import evaluation_id, entry_intent_id


def _json(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'), allow_nan=False)


def _digest(value):
    return hashlib.sha256(_json(value).encode()).hexdigest()


def _amount(value, *, zero=False):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError('Finite numeric fixture required')
    if value < 0 or (not zero and value == 0):
        raise ValueError('Invalid fixture amount')
    return value


class SyntheticLedger:
    TABLES = {'hybrid_contract_accounts', 'hybrid_evaluations', 'hybrid_decisions',
              'hybrid_entry_intents', 'hybrid_fills', 'hybrid_ledger_events'}
    BINDINGS = {'base_policy', 'feature', 'model', 'intelligence_policy',
                'execution_policy', 'cost', 'risk_forecast', 'events'}

    def __init__(self, connection):
        self.db = connection
        self.db.row_factory = sqlite3.Row
        tables = {r[0] for r in self.db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        if tables - self.TABLES:
            raise ValueError('Synthetic contract requires an isolated database')
        self.db.execute('PRAGMA foreign_keys=ON')
        self.db.executescript('''
            CREATE TABLE IF NOT EXISTS hybrid_contract_accounts (
                run TEXT NOT NULL, arm TEXT NOT NULL, version INTEGER NOT NULL,
                cash REAL NOT NULL CHECK(cash>=0), reserved_cash REAL NOT NULL CHECK(reserved_cash>=0),
                committed_risk REAL NOT NULL CHECK(committed_risk>=0), risk_limit REAL NOT NULL,
                protection_pending INTEGER NOT NULL DEFAULT 0,
                classification TEXT NOT NULL CHECK(classification='SYNTHETIC_CONTRACT_ONLY'),
                PRIMARY KEY(run,arm), CHECK(reserved_cash<=cash), CHECK(committed_risk<=risk_limit));
            CREATE TABLE IF NOT EXISTS hybrid_evaluations (
                evaluation_id TEXT PRIMARY KEY, run TEXT NOT NULL, arm TEXT NOT NULL,
                signal_id TEXT NOT NULL, payload TEXT NOT NULL,
                FOREIGN KEY(run,arm) REFERENCES hybrid_contract_accounts(run,arm));
            CREATE TABLE IF NOT EXISTS hybrid_decisions (
                evaluation_id TEXT PRIMARY KEY REFERENCES hybrid_evaluations(evaluation_id),
                payload TEXT NOT NULL);
            CREATE TABLE IF NOT EXISTS hybrid_entry_intents (
                intent_id TEXT PRIMARY KEY, run TEXT NOT NULL, arm TEXT NOT NULL,
                signal_id TEXT NOT NULL, evaluation_id TEXT NOT NULL REFERENCES hybrid_evaluations(evaluation_id),
                quantity REAL NOT NULL CHECK(quantity>0), filled REAL NOT NULL DEFAULT 0,
                reserve_cash REAL NOT NULL, spent REAL NOT NULL DEFAULT 0,
                UNIQUE(run,arm,signal_id), CHECK(filled>=0 AND filled<=quantity),
                CHECK(spent>=0 AND spent<=reserve_cash),
                FOREIGN KEY(run,arm) REFERENCES hybrid_contract_accounts(run,arm));
            CREATE TABLE IF NOT EXISTS hybrid_fills (
                intent_id TEXT NOT NULL REFERENCES hybrid_entry_intents(intent_id),
                event_id TEXT NOT NULL, payload TEXT NOT NULL,
                PRIMARY KEY(intent_id,event_id));
            CREATE TABLE IF NOT EXISTS hybrid_ledger_events (
                run TEXT NOT NULL, arm TEXT NOT NULL, event_id TEXT NOT NULL, payload TEXT NOT NULL,
                PRIMARY KEY(run,arm,event_id),
                FOREIGN KEY(run,arm) REFERENCES hybrid_contract_accounts(run,arm));
        ''')

    @contextmanager
    def transaction(self):
        self.db.execute('BEGIN IMMEDIATE')
        try:
            yield
            self.db.commit()
        except BaseException:
            self.db.rollback()
            raise

    def create_account(self, run, arm, *, cash, risk_limit):
        _amount(cash)
        _amount(risk_limit)
        if not run or not arm or risk_limit > cash:
            raise ValueError('Invalid isolated fixture account')
        with self.transaction():
            self.db.execute('INSERT INTO hybrid_contract_accounts VALUES(?,?,0,?,0,0,?,0,?)',
                            (run, arm, cash, risk_limit, 'SYNTHETIC_CONTRACT_ONLY'))

    def account(self, run, arm):
        row = self.db.execute('SELECT * FROM hybrid_contract_accounts WHERE run=? AND arm=?', (run, arm)).fetchone()
        if row is None:
            raise ValueError('Unknown isolated account')
        result = dict(row)
        result['state_hash'] = _digest(result)
        return result

    def record_evaluation(self, *, run, arm, signal_id, expected_version, portfolio_hash,
                          bindings, timeline, quantity, reserve_cash, reserve_risk):
        if set(bindings) != self.BINDINGS or any(not isinstance(v, str) or not v for v in bindings.values()):
            raise ValueError('Missing or unknown evaluation binding')
        if type(expected_version) is not int or expected_version < 0 or not portfolio_hash:
            raise ValueError('Explicit portfolio version/hash required')
        DecisionTimeline(**timeline)
        for value in (quantity, reserve_cash, reserve_risk):
            _amount(value)
        payload = dict(run=run, arm=arm, signal_id=signal_id, expected_version=expected_version,
                       portfolio_hash=portfolio_hash, bindings=bindings, timeline=timeline,
                       quantity=quantity, reserve_cash=reserve_cash, reserve_risk=reserve_risk)
        eid = evaluation_id(signal_id, payload)
        encoded = _json(payload)
        with self.transaction():
            self.account(run, arm)
            prior = self.db.execute('SELECT payload FROM hybrid_evaluations WHERE evaluation_id=?', (eid,)).fetchone()
            if prior is not None and prior['payload'] != encoded:
                raise ValueError('Evaluation identity conflict')
            self.db.execute('INSERT OR IGNORE INTO hybrid_evaluations VALUES(?,?,?,?,?)', (eid, run, arm, signal_id, encoded))
        return eid

    def evaluation(self, eid):
        row = self.db.execute('SELECT payload FROM hybrid_evaluations WHERE evaluation_id=?', (eid,)).fetchone()
        if row is None:
            raise ValueError('Unknown evaluation')
        return json.loads(row['payload'])

    def commit_entry(self, eid, *, committed_at, inject_fault=False):
        with self.transaction():
            e = self.evaluation(eid)
            t = DecisionTimeline(**e['timeline'])
            # Real commit time is supplied by the synthetic logical clock, not
            # silently taken from model output or moved back to signal time.
            if committed_at != t.decision_committed_at:
                raise ValueError('Commit time differs from evaluation contract')
            existing = self.db.execute('SELECT intent_id FROM hybrid_entry_intents WHERE run=? AND arm=? AND signal_id=?',
                                       (e['run'], e['arm'], e['signal_id'])).fetchone()
            if existing:
                return {'status': 'IDEMPOTENT', 'intent_id': existing['intent_id']}
            prior = self.db.execute('SELECT payload FROM hybrid_decisions WHERE evaluation_id=?', (eid,)).fetchone()
            if prior:
                return json.loads(prior['payload'])
            a = self.account(e['run'], e['arm'])
            status = 'ACCEPTED'
            if a['version'] != e['expected_version'] or a['state_hash'] != e['portfolio_hash']:
                status = 'ABSTAIN_PORTFOLIO_CHANGED'
            elif a['protection_pending']:
                status = 'ABSTAIN_PROTECTION_PENDING'
            elif a['reserved_cash'] + e['reserve_cash'] > a['cash'] or a['committed_risk'] + e['reserve_risk'] > a['risk_limit']:
                status = 'REJECTED_BUDGET'
            result = {'status': status, 'intent_id': None}
            if status == 'ACCEPTED':
                iid = entry_intent_id(e['run'], e['arm'], e['signal_id'])
                result['intent_id'] = iid
                self.db.execute('INSERT INTO hybrid_entry_intents VALUES(?,?,?,?,?,?,0,?,0)',
                                (iid, e['run'], e['arm'], e['signal_id'], eid, e['quantity'], e['reserve_cash']))
                cursor = self.db.execute('''UPDATE hybrid_contract_accounts
                    SET version=version+1,reserved_cash=reserved_cash+?,committed_risk=committed_risk+?
                    WHERE run=? AND arm=? AND version=?''',
                    (e['reserve_cash'], e['reserve_risk'], e['run'], e['arm'], e['expected_version']))
                if cursor.rowcount != 1:
                    raise RuntimeError('Concurrent portfolio change')
            if inject_fault:
                raise RuntimeError('injected transaction failure')
            self.db.execute('INSERT INTO hybrid_decisions VALUES(?,?)', (eid, _json(result)))
            self.db.execute('INSERT INTO hybrid_ledger_events VALUES(?,?,?,?)',
                            (e['run'], e['arm'], 'decision:' + eid, _json(result)))
            return result

    def protection_pending(self, run, arm, event_id, *, at, reason):
        _amount(at, zero=True)
        if reason != 'EXIT_PENDING_NO_VALID_QUOTE':
            raise ValueError('This M1 fixture only models pending protection, never fabricated exits')
        payload = _json({'status': reason, 'at': at})
        with self.transaction():
            self.account(run, arm)
            prior = self.db.execute('SELECT payload FROM hybrid_ledger_events WHERE run=? AND arm=? AND event_id=?',
                                    (run, arm, event_id)).fetchone()
            if prior is not None:
                if prior['payload'] != payload:
                    raise ValueError('Protection event conflict')
                return json.loads(payload)
            self.db.execute('UPDATE hybrid_contract_accounts SET version=version+1, protection_pending=1 WHERE run=? AND arm=?', (run, arm))
            self.db.execute('INSERT INTO hybrid_ledger_events VALUES(?,?,?,?)', (run, arm, event_id, payload))
            return json.loads(payload)

    def fill(self, intent, event_id, *, event_at, received_at, quantity, spent_cash):
        _amount(quantity)
        _amount(spent_cash)
        payload = _json(dict(event_at=event_at, received_at=received_at, quantity=quantity, spent_cash=spent_cash))
        with self.transaction():
            row = self.db.execute('SELECT * FROM hybrid_entry_intents WHERE intent_id=?', (intent,)).fetchone()
            if row is None:
                raise ValueError('Unknown approved intent')
            prior = self.db.execute('SELECT payload FROM hybrid_fills WHERE intent_id=? AND event_id=?', (intent, event_id)).fetchone()
            if prior is not None:
                if prior['payload'] != payload:
                    raise ValueError('Fill event conflict')
                return {'status': 'IDEMPOTENT'}
            e = self.evaluation(row['evaluation_id'])
            if not DecisionTimeline(**e['timeline']).permits_fill(event_at, received_at):
                raise ValueError('Fill time is not eligible')
            if row['filled'] + quantity > row['quantity'] or row['spent'] + spent_cash > row['reserve_cash']:
                raise ValueError('Fill exceeds approved quantity or cash')
            a = self.account(row['run'], row['arm'])
            if a['protection_pending']:
                raise ValueError('Protection pending blocks new synthetic fills')
            complete = row['filled'] + quantity == row['quantity']
            released = row['reserve_cash'] - row['spent'] if complete else spent_cash
            self.db.execute('UPDATE hybrid_entry_intents SET filled=filled+?,spent=spent+? WHERE intent_id=?',
                            (quantity, spent_cash, intent))
            self.db.execute('''UPDATE hybrid_contract_accounts SET version=version+1,
                cash=cash-?,reserved_cash=reserved_cash-? WHERE run=? AND arm=?''',
                (spent_cash, released, row['run'], row['arm']))
            self.db.execute('INSERT INTO hybrid_fills VALUES(?,?,?)', (intent, event_id, payload))
            self.db.execute('INSERT INTO hybrid_ledger_events VALUES(?,?,?,?)',
                            (row['run'], row['arm'], 'fill:' + intent + ':' + event_id, payload))
            return {'status': 'FILLED' if complete else 'PARTIAL'}

    def count(self, table):
        if table not in self.TABLES:
            raise ValueError('Unknown synthetic table')
        return self.db.execute('SELECT COUNT(*) FROM ' + table).fetchone()[0]

    def close(self):
        self.db.close()


class ContractWriter:
    """Single-thread logical scheduling fixture. Does not start model workers."""

    def __init__(self, ledger):
        self.ledger = ledger
        self.queue = []
        self.sequence = 0
        self.model_futures = []
        self.halted = False

    def enqueue_model(self, future):
        self.model_futures.append(future)

    def _enqueue(self, priority, at, callback):
        if self.halted:
            raise RuntimeError('Synthetic writer halted; explicit recovery required')
        self.sequence += 1
        heapq.heappush(self.queue, (at, priority, self.sequence, callback))

    def enqueue_entry(self, eid, *, at):
        self._enqueue(2, at, lambda: self.ledger.commit_entry(eid, committed_at=at))

    def enqueue_protection(self, run, arm, event_id, *, at, reason):
        self._enqueue(0, at, lambda: self.ledger.protection_pending(run, arm, event_id, at=at, reason=reason))

    def drain_ready(self):
        # Never call result() on an unfinished model; protection uses its own
        # ready queue. A production runtime still needs resource/latency tests.
        if self.halted:
            raise RuntimeError('Synthetic writer halted; explicit recovery required')
        results = []
        while self.queue:
            _, _, _, callback = heapq.heappop(self.queue)
            try:
                results.append(callback())
            except BaseException:
                self.halted = True
                raise
        return results
